### PR TITLE
MP-1410. Manage funds amount send to red-bank.

### PR DESCRIPTION
**Pull request by piobab**
Fixes to managing funds.

### CODE REVIEW

**Review by dancreee — APPROVED** [review]
Nice so essentially the changes are

a. previously we were passing 100% of a denoms funds in the first msg, now we specify the amount in each message so we are not sending 100%
b. at the end of the liquidate many we just refund all accounts held by the contract to the tx sender encase the redbank does any refunds - this can be removed when we hold funds in contract eventually

**Comment by piobab** [comment]
> Nice so essentially the changes are
> 
> a. previously we were passing 100% of a denoms funds in the first msg, now we specify the amount in each message so we are not sending 100% b. at the end of the liquidate many we just refund all accounts held by the contract to the tx sender encase the redbank does any refunds - this can be removed when we hold funds in contract eventually

Exactly.

**Review by grod220 — APPROVED** [review]
LGTM. Think cw-multi-test is helpful for testing in these kinds of cases where two contracts interact and you need to query the bankmodule and other state in both.

**Comment by piobab** [comment]
> LGTM. Think cw-multi-test is helpful for testing in these kinds of cases where two contracts interact and you need to query the bankmodule and other state in both.

100% agreed on that field - we will use more mutlitests.

**Pull request merged**
